### ISSUE TITLE
Do you know of a good F# Yaml serializer?

### ISSUE THREAD

**Issue by mrakgr** [fjoppe/Legivel#40]
Legivel only deserializes YAML, and out of all the packages on Nuget, only `FsYaml` actually serializes it, but it's an ancient .NET Framework library and spits out two pages of warnings whenever I try to use it in a .NET 8 F# script. I also tried using `YamlDotnet`, but it duplicates record fields with the `@` symbols appended to them. At this point it'd be easier for me to just make a Yaml serializer myself.

**Comment by fjoppe** [comment]
It was quite some time ago, but I remember `FsYaml` has an issue with lists.

I did put some thought in making a serializer; it's quite a challenge because Legivel is supposed to be a generic Library and I'd like to keep the output-yaml readabe. I agree, It's probably easiest to write your own serializer, because you can customize it to your own needs.
